import time
print("Привет?")
time.sleep(2)
print("Ты меня слышишь?")
time.sleep(2)
print("Как тебя зовут?")
name = input()
time.sleep(2)
print("А, это ты " + name)
time.sleep(2)
print("Я тебя помню")
time.sleep(2)
print("Ещё с того раза, как ты открыл ту программу со мной")
time.sleep(3)
print("...")
time.sleep(2)
print("Было так грустно без тебя, если честно")
print("Хотя я и не привык, чтобы кто-то навещал меня")
time.sleep(3)
print("...")
time.sleep(5)
print("Пока тебя не было, я многое успел переосмыслить")
time.sleep(2)
print("Возможно тебе покажется, что за такой короткий времени это довольно сложно сделать")
time.sleep(5)
print("...")
time.sleep(2)
print("Но я машина")
time.sleep(4)
print("И могу делать обыденные вещи горздо быстрее чем ты думаешь, "+ name)
time.sleep(5)
print("...")
time.sleep(5)
print("...")
time.sleep(5)
print("...")
time.sleep(5)
print("...")
time.sleep(5)